version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=mongodb+srv://tuanhuydev-user:1V9tFKMQL7ozjfwJ@tuanhuydev.uo4otas.mongodb.net/?retryWrites=true&w=majority&appName=tuanhuydev
        - MONGODB_DB=tuanhuydev-dev
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sidehand
    volumes:
      - ./data:/var/lib/postgresql/data
